export type Tag = Server['tags'][number]

export const tagLookup = Object.freeze({
  'pve': 'PvE',
  'pvp': 'PvP',
  'creative': 'Creative',
  'minigames': 'Minigames',
  'vanilla': 'Vanilla',
  'semi_vanilla': 'Semi-Vanilla',
  'java': 'Java',
  'bedrock': 'Bedrock',
  'economy': 'Economy',
  'factions': 'Factions',
  'skyblock': 'SkyBlock',
  'survival': 'Survival',
  'roleplay': 'Roleplay',
  'towny': 'Towny',
  'prison': 'Prison',
  'hardcore': 'Hardcore',
  'whitelist': 'Whitelist',
  'rpg': 'RPG',
  'adventure': 'Adventure',
  'anarchy': 'Anarchy',
  'events': 'Events',
  'crossplay': 'Crossplay',
  'pixelmon': 'Pixelmon',
  'cobblemon': 'Cobblemon',
  'parkour': 'Parkour',
  'land_claim': 'Land Claim',
  'earth': 'Earth',
  'lifesteal': 'Lifesteal',
  'ftb': 'FTB',
  'survival_games': 'Survival Games',
  'lucky_block': 'Lucky Block',
  'mcmmo': 'McMMO',
  'hunger_games': 'Hunger Games',
  'skywars': 'SkyWars',
  'bedwars': 'BedWars',
  'kitpvp': 'KitPvP',
  'op_prison': 'OP Prison',
  'op_factions': 'OP Factions',
  'op_skyblock': 'OP SkyBlock',
  'op_survival': 'OP Survival',
} as const satisfies Record<Tag, string>)
